language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.0"
  - "4.1"
  - "4"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
sudo: false
script: grunt