/*globals describe, beforeEach, inject, it, expect, setFixtures, $*/
'use strict';

describe('Controller: ganttcharthyperlibraryCtrl', function () {

    // load the controller's module
    beforeEach(module('javascriptGraphLibrariesApp'));

    var ganttcharthyperlibraryCtrl,
            scope;

    // Initialize the controller and a mock scope
    beforeEach(inject(function ($controller, $rootScope) {
        scope = $rootScope.$new();
        var page = "";
        page += "<div class=\"row\">";
        page += "    <div class=\"box\">";
        page += "        <div class=\"col-lg-12\"> <span us-spinner=\"{radius:30, width:8, length: 16}\"><\/span>";
        page += "            <div id=\"gantt-chart-hyper-library-main\"";
        page += "                 class=\"page-container\">";
        page += "                <div class=\"ribbonContainer\">";
        page += "                    <div class=\"ribbonPanel\">";
        page += "                        <div class=\"ribbonHeader\">Items<\/div>";
        page += "                        <div";
        page += "                            class=\"ribbonCommandsArea\">";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"addNewItem();\"";
        page += "                                   title=\"Add new item\"><img src=\"Images\/AddNew.png\"";
        page += "                                                          alt=\"Add new\"";
        page += "                                                          \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"insertNewItem();\"";
        page += "                                   title=\"Insert new item before selection\"><img src=\"Images\/InsertNew.png\"";
        page += "                                                                              alt=\"Insert new\"";
        page += "                                                                              \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"decreaseItemIndentation();\"";
        page += "                                   title=\"Decrease selected item indentation\"><img src=\"Images\/DecreaseIndentation.png\"";
        page += "                                                                                alt=\"Increase indentation\"";
        page += "                                                                                \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"increaseItemIndentation();\"";
        page += "                                   title=\"Increase selected item indentation\"><img src=\"Images\/IncreaseIndentation.png\"";
        page += "                                                                                alt=\"Increase indentation\"";
        page += "                                                                                \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"deleteItem();\"";
        page += "                                   title=\"Delete selected item\"><img src=\"Images\/Delete.png\"";
        page += "                                                                  alt=\"Delete selected item\"";
        page += "                                                                  \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"setCustomBarColorToItem();\"";
        page += "                                   title=\"Set custom bar color to selected item\"><img src=\"Images\/SetColor.png\"";
        page += "                                                                                   alt=\"Set color\"";
        page += "                                                                                   \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"copyItem();\"";
        page += "                                   title=\"Copy selected item\"><img src=\"Images\/Copy.png\"";
        page += "                                                                alt=\"Copy\"";
        page += "                                                                \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"pasteItem();\"";
        page += "                                   title=\"Paste after selected item\"><img src=\"Images\/Paste.png\"";
        page += "                                                                       alt=\"Paste\"";
        page += "                                                                       \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"moveItemUp();\"";
        page += "                                   title=\"Move selected item up\"><img src=\"Images\/MoveUp.png\"";
        page += "                                                                   alt=\"Move up\"";
        page += "                                                                   \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"moveItemDown();\"";
        page += "                                   title=\"Move selected item down\"><img src=\"Images\/MoveDown.png\"";
        page += "                                                                     alt=\"Move down\"";
        page += "                                                                     \/><\/a>";
        page += "                            <\/div>";
        page += "                        <\/div>";
        page += "                    <\/div>";
        page += "                    <div class=\"ribbonPanel\">";
        page += "                        <div class=\"ribbonHeader\">Timeline\/Schedule<\/div>";
        page += "                        <div class=\"ribbonCommandsArea\">";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"setCustomScales();\"";
        page += "                                   title=\"Set custom scales\"><img src=\"Images\/CustomScales.png\"";
        page += "                                                               alt=\"Custom scales\"";
        page += "                                                               \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"zoomIn();\"";
        page += "                                   title=\"Zoom in\"><img src=\"Images\/ZoomIn.png\"";
        page += "                                                     alt=\"Zoom in\"";
        page += "                                                     \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"decreaseTimelinePage();\"";
        page += "                                   title=\"Move towards past\"><img src=\"Images\/DecreaseTimelinePage.png\"";
        page += "                                                               alt=\"Decrease timeline page\"";
        page += "                                                               \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"increaseTimelinePage();\"";
        page += "                                   title=\"Move towards future\"><img src=\"Images\/IncreaseTimelinePage.png\"";
        page += "                                                                 alt=\"Increase timeline page\"";
        page += "                                                                 \/><\/a>";
        page += "                            <\/div>";
        page += "                        <\/div>";
        page += "                    <\/div>";
        page += "                    <div class=\"ribbonPanel\">";
        page += "                        <div class=\"ribbonHeader\">Project tools<\/div>";
        page += "                        <div";
        page += "                            class=\"ribbonCommandsArea\">";
        page += "                            <div class=\"ribbonCommand toggle pressed\"";
        page += "                                 id=\"toggleBaselineCommand\">";
        page += "                                <a ng-click=\"toggleBaseline();\"";
        page += "                                   title=\"Hide\/display baseline\"><img src=\"Images\/Baseline.png\"";
        page += "                                                                   alt=\"Baseline\"";
        page += "                                                                   \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand toggle\"";
        page += "                                 id=\"highlightCriticalPathCommand\">";
        page += "                                <a ng-click=\"highlightCriticalPath();\"";
        page += "                                   title=\"Highlight\/refresh critical path\"><img src=\"Images\/CriticalPath.png\"";
        page += "                                                                             alt=\"Critical path\"";
        page += "                                                                             \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"splitRemainingWork();\"";
        page += "                                   title=\"Split work upon completion point in order to be able to reschedule remaining work separately\"><img src=\"Images\/SplitRemainingWork.png\"";
        page += "                                                                                                                                          alt=\"Split remaining work\"";
        page += "                                                                                                                                          \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand toggle pressed\"";
        page += "                                 id=\"toggleDependencyConstraintsCommand\">";
        page += "                                <a ng-click=\"toggleDependencyConstraints();\"";
        page += "                                   title=\"Disable\/enable automatic scheduling\"><img src=\"Images\/DependencyConstraints.png\"";
        page += "                                                                                 alt=\"Dependency constraints\"";
        page += "                                                                                 \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"levelResources();\"";
        page += "                                   title=\"Level resources\"><img src=\"Images\/LevelResources.png\"";
        page += "                                                             alt=\"Level resources\"";
        page += "                                                             \/><\/a>";
        page += "                            <\/div>";
        page += "                        <\/div>";
        page += "                    <\/div>";
        page += "                    <div class=\"ribbonPanel\">";
        page += "                        <div class=\"ribbonHeader\">Other views<\/div>";
        page += "                        <div class=\"ribbonCommandsArea\">";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"scheduleChart();\"";
        page += "                                   title=\"Schedule Chart\"><img src=\"Images\/ScheduleChart.png\"";
        page += "                                                            alt=\"Schedule Chart\"";
        page += "                                                            \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"loadChart();\"";
        page += "                                   title=\"Load Chart\"><img src=\"Images\/LoadChart.png\"";
        page += "                                                        alt=\"Load Chart\"";
        page += "                                                        \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"pertChart();\"";
        page += "                                   title=\"PERT Chart\"><img src=\"Images\/PertChart.png\"";
        page += "                                                        alt=\"PERT Chart\"";
        page += "                                                        \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"networkDiagram();\"";
        page += "                                   title=\"Network Diagram\"><img src=\"Images\/NetworkDiagram.png\"";
        page += "                                                             alt=\"Network Diagram\"";
        page += "                                                             \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"projectStatistics();\"";
        page += "                                   title=\"Project statistics\"><img src=\"Images\/ProjectStatistics.png\"";
        page += "                                                                alt=\"Project statistics\"";
        page += "                                                                \/><\/a>";
        page += "                            <\/div>";
        page += "                        <\/div>";
        page += "                    <\/div>";
        page += "                    <div class=\"ribbonPanel\">";
        page += "                        <div class=\"ribbonHeader\">XML and printing<\/div>";
        page += "                        <div";
        page += "                            class=\"ribbonCommandsArea\">";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"loadProjectXml();\"";
        page += "                                   title=\"Import Project XML content\"><img src=\"Images\/LoadProjectXml.png\"";
        page += "                                                                        alt=\"Import Project XML\"";
        page += "                                                                        \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"saveProjectXml();\"";
        page += "                                   title=\"Export Project XML content\"><img src=\"Images\/SaveProjectXml.png\"";
        page += "                                                                        alt=\"Export Project XML\"";
        page += "                                                                        \/><\/a>";
        page += "                            <\/div>";
        page += "                            <div class=\"ribbonCommand\">";
        page += "                                <a ng-click=\"print();\"";
        page += "                                   title=\"Print\"><img src=\"Images\/Print.png\"";
        page += "                                                   alt=\"Print\" \/><\/a>";
        page += "                            <\/div>";
        page += "                        <\/div>";
        page += "                    <\/div>";
        page += "                <\/div>";
        page += "                <div id=\"ganttChartView\" style=\"height: 480px\">...<\/div>";
        page += "                <div id=\"loadProjectXmlPanel\"";
        page += "                     style=\"display: none\">";
        page += "                    <div class=\"extraPanel\">";
        page += "                        <div class=\"extraPanelCommandsArea\">";
        page += "                            <div><a ng-click=\"closeLoadProjectXml();\">Close<\/a><\/div>";
        page += "                        <\/div>";
        page += "                        <div class=\"extraPanelHeader\">Import Project XML<\/div>";
        page += "                        <div";
        page += "                            class=\"extraPanelContent\" style=\"margin: 4px 0px 4px 0px\">";
        page += "                            Enter\/paste Project XML content";
        page += "                            to load:";
        page += "                            <div style=\"margin: 4px 0px 4px 0px\">";
        page += "                                <textarea id=\"loadProjectXmlInput\"";
        page += "                                          spellcheck=\"false\" cols=\"120\"";
        page += "                                          rows=\"4\">&lt;Project\/&gt;<\/textarea>                    <\/div> <a id=\"loadProjectXmlButton\"";
        page += "                                                                                              ng-click=\"loadProjectXmlContent();\"";
        page += "                                                                                              title=\"Load Project XML content\">Load<\/a>                <\/div>";
        page += "                    <\/div>";
        page += "                <\/div>";
        page += "                <div id=\"saveProjectXmlPanel\" style=\"display: none\">";
        page += "                    <div class=\"extraPanel\">";
        page += "                        <div class=\"extraPanelCommandsArea\">";
        page += "                            <div><a ng-click=\"closeSaveProjectXml();\">Close<\/a><\/div>";
        page += "                        <\/div>";
        page += "                        <div class=\"extraPanelHeader\">Export Project XML<\/div>";
        page += "                        <div class=\"extraPanelContent\"";
        page += "                             style=\"margin: 4px 0px 4px 0px\">";
        page += "                            View\/copy Project XML content:";
        page += "                            <div";
        page += "                                style=\"margin: 4px 0px 4px 0px\">";
        page += "                                <textarea id=\"saveProjectXmlOutput\"";
        page += "                                          readonly=\"readonly\" cols=\"120\"";
        page += "                                          rows=\"4\"><\/textarea> <\/div>";
        page += "                        <\/div>";
        page += "                    <\/div>";
        page += "                <\/div>";
        page += "                <div id=\"scheduleChartPanel\" style=\"display: none\">";
        page += "                    <div class=\"extraPanel\">";
        page += "                        <div class=\"extraPanelCommandsArea\">";
        page += "                            <div><a ng-click=\"closeScheduleChartView();\">Close<\/a><\/div>";
        page += "                        <\/div>";
        page += "                        <div class=\"extraPanelHeader\">Schedule Chart<\/div>";
        page += "                    <\/div>";
        page += "                    <div id=\"scheduleChartView\" style=\"height: 124px\">...<\/div>";
        page += "                <\/div>";
        page += "                <div id=\"loadChartPanel\" style=\"display: none\">";
        page += "                    <div class=\"extraPanel\">";
        page += "                        <div class=\"extraPanelCommandsArea\">";
        page += "                            <div><a ng-click=\"closeLoadChartView();\">Close<\/a><\/div>";
        page += "                        <\/div>";
        page += "                        <div class=\"extraPanelHeader\">Load Chart<\/div>";
        page += "                        <div class=\"extraPanelContent\">";
        page += "                            Resource filter: <select id=\"loadChartResourceFilter\"";
        page += "                                                     style=\"margin: 2px 0px\" onchange=\"loadChartResourceFilterChanged()\">";
        page += "                                <option value=\"\">(All)<\/option>";
        page += "                            <\/select> <\/div>";
        page += "                    <\/div>";
        page += "                    <div id=\"loadChartView\" style=\"height: 124px\">...<\/div>";
        page += "                <\/div>";
        page += "                <div id=\"pertChartPanel\" style=\"display: none\">";
        page += "                    <div class=\"extraPanel\">";
        page += "                        <div class=\"extraPanelCommandsArea\">";
        page += "                            <div><a ng-click=\"closePertChartView();\">Close<\/a><\/div>";
        page += "                        <\/div>";
        page += "                        <div class=\"extraPanelHeader\">PERT Chart<\/div>";
        page += "                    <\/div>";
        page += "                    <div id=\"pertChartView\" style=\"height: 196px\">...<\/div>";
        page += "                <\/div>";
        page += "                <div id=\"networkDiagramPanel\" style=\"display: none\">";
        page += "                    <div class=\"extraPanel\">";
        page += "                        <div class=\"extraPanelCommandsArea\">";
        page += "                            <div><a ng-click=\"closeNetworkDiagramView();\">Close<\/a><\/div>";
        page += "                        <\/div>";
        page += "                        <div class=\"extraPanelHeader\">Network Diagram<\/div>";
        page += "                    <\/div>";
        page += "                    <div id=\"networkDiagramView\" style=\"height: 196px\">...<\/div>";
        page += "                <\/div>";
        page += "            <\/div>";
        page += "        <\/div>";
        page += "    <\/div>";
        page += "<\/div>";

        setFixtures(page);
        ganttcharthyperlibraryCtrl = $controller('ganttcharthyperlibraryCtrl', {
            $scope: scope
        });
    }));

    it('The gantt-chart-hyper-library-main div should not be empty', function () {
        expect($("#gantt-chart-hyper-library-main #ganttChartView").html() === "...").toBe(false);
    });
});
