 /*exported jglGetTranslations*/
 function jglGetTranslations() {
  return {
    EN_US: {
      //index.html
      APP_HEADLINE: 'Graph representation with JS',
      APP_HEADLINE_UNDERTITLE: 'Corporate development project (THM)',
      APP_TOGGLE_NAVIGATION: 'Toggle Navigation',
      APP_HEADLINE_LARGE: 'Graph representation with JS',
      APP_NAV_HOME: 'Home',
      APP_NAV_JOINTJS: 'JointJS',
      APP_NAV_D3: 'D3',
      APP_NAV_VIS: 'Vis.js',
      APP_NAV_JSPLUMB: 'jsPlumb',
      APP_NAV_CYTOSCAPE: 'Cytoscape.js',
      APP_NAV_DRACULA: 'Dracula and RaphaelJs',
      APP_NAV_FABRIC: 'Fabric',
      APP_NAV_SETTINGS: 'Settings',
      APP_FOOTER_COMPAGNY: 'Department of mathematics, science and computer sciences (THM)',
      APP_FOOTER_IMPRINT: 'Imprint',
      APP_FOOTER_PRIVACY: 'Privacy',
      //vis.html
      VIS_HEADLINE: 'This example demonstrates dynamically adding, updating and removing nodes and edges using a DataSet.',
      VIS_ADJUST: 'Adjust',
      VIS_NODE: 'Node',
      VIS_NODE_ID: 'Id',
      VIS_NODE_LABEL: 'Label',
      VIS_NODE_ACTION: 'Action',
      VIS_NODE_ADD: 'Add',
      VIS_NODE_UPDATE: 'Update',
      VIS_NODE_REMOVE: 'Remove',
      VIS_EDGE: 'Edge',
      VIS_EDGE_ID: 'Id',
      VIS_EDGE_FROM: 'From',
      VIS_EDGE_TO: 'To',
      VIS_EDGE_ACTION: 'Action',
      VIS_EDGE_ADD: 'Add',
      VIS_EDGE_UPDATE: 'Update',
      VIS_EDGE_REMOVE: 'Remove',
      VIS_VIEW: 'View',
      VIS_VIEW_NODE: 'Nodes',
      VIS_VIEW_EDGES: 'Edges',
      VIS_VIEW_NETWORK: 'Network',
      //config.html
      CONFIG_LANGUAGE_HEADER: 'Language - Configure your language',
      CONFIG_PERFORMANCE_HEADER: 'Performance - Ability to work under big data',
      CONFIG_PERFORMANCE_DATA_SOURCE: 'Data Source :'
    },
    DE_DE: {
      //index.html
      APP_HEADLINE: 'Graphendarstellung mit JS',
      APP_HEADLINE_UNDERTITLE: 'Betriebliches Entwicklungsprojekt (THM)',
      APP_TOGGLE_NAVIGATION: 'Toggle-Navigation',
      APP_HEADLINE_LARGE: 'Graphendarstellung mit JS',
      APP_NAV_HOME: 'Start',
      APP_NAV_JOINTJS: 'JointJS',
      APP_NAV_D3: 'D3',
      APP_NAV_VIS: 'Vis.js',
      APP_NAV_JSPLUMB: 'jsPlumb',
      APP_NAV_CYTOSCAPE: 'Cytoscape.js',
      APP_NAV_DRACULA: 'Dracula und RaphaelJs',
      APP_NAV_FABRIC: 'Fabric',
      APP_NAV_SETTINGS: 'Einstellungen',
      APP_FOOTER_COMPAGNY: 'Fachbereich Mathematik, Naturwissenschaften und Informatik (THM)',
      APP_FOOTER_IMPRINT: 'Impressum',
      APP_FOOTER_PRIVACY: 'Datenschutz',
      //vis.html
      VIS_HEADLINE: 'Dieses Beispiel zeigt, wie Knoten und Kanten mit Vis.js manipuliert werden koennen.',
      VIS_ADJUST: 'Einstellen',
      VIS_NODE: 'Knoten',
      VIS_NODE_ID: 'Id',
      VIS_NODE_LABEL: 'Label',
      VIS_NODE_ACTION: 'Aktion',
      VIS_NODE_ADD: 'Hinzufuegen',
      VIS_NODE_UPDATE: 'Aktualisieren',
      VIS_NODE_REMOVE: 'Entfernen',
      VIS_EDGE: 'Kante',
      VIS_EDGE_ID: 'Id',
      VIS_EDGE_FROM: 'Von',
      VIS_EDGE_TO: 'Bis',
      VIS_EDGE_ACTION: 'Aktion',
      VIS_EDGE_ADD: 'Hinzufuegen',
      VIS_EDGE_UPDATE: 'Aktualisieren',
      VIS_EDGE_REMOVE: 'Entfernen',
      VIS_VIEW: 'Ansicht',
      VIS_VIEW_NODE: 'Knoten',
      VIS_VIEW_EDGES: 'Kanten',
      VIS_VIEW_NETWORK: 'Netzwerk',
      //config.html
      CONFIG_LANGUAGE_HEADER: 'Spracheinstellung - Konfigurieren Sie Ihre Sprache',
      CONFIG_PERFORMANCE_HEADER: 'Leistung - Faehigkeit, groesse Datenmenge zu verarbeiten',
      CONFIG_PERFORMANCE_DATA_SOURCE: 'Datenquelle: '
    }
  };
}
